apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: kubequest
  labels:
    app.kubernetes.io/name: kubequest-app
spec:
  selector:
    app.kubernetes.io/name: kubequest-app
  ports:
    - port: 80
      targetPort: 80
